FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

COPY . /app/

CMD ["pytest", "--cov=src"]

CMD ["flake8", "src"]